# device.mk - Infinix Hot 60 Pro Plus (x6886)
# Pulls vendor blobs + declares recovery HAL packages.
# Blobs are listed via proprietary-files.txt (de-duplicated by setup-makefiles.sh)
# so we do NOT hit duplicate PRODUCT_COPY_FILES errors at build time.

$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit_only.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/base.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/emulated_storage.mk)

# Virtual A/B OTA (launch with vendor ramdisk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/launch_with_vendor_ramdisk.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/virtual_ab_ota/compression.mk)
ENABLE_VIRTUAL_AB := true

# Dynamic partitions
PRODUCT_USE_DYNAMIC_PARTITIONS := true
PRODUCT_SHIPPING_API_LEVEL := 34
PRODUCT_TARGET_VNDK_VERSION := 34

PRODUCT_PROPERTY_OVERRIDES += ro.twrp.vendor_boot=true

# --- Boot control HAL (MTK) ---
PRODUCT_PACKAGES += \
    android.hardware.boot@1.2-mtkimpl \
    android.hardware.boot@1.2-mtkimpl.recovery

# --- Fastbootd ---
PRODUCT_PACKAGES += \
    android.hardware.fastboot@1.0-impl-mock \
    fastbootd

# --- Health HAL ---
PRODUCT_PACKAGES += \
    android.hardware.health@2.1-impl \
    android.hardware.health@2.1-service

# --- Keymaster / Keymint (Trustonic TEE - required for decrypt on this device) ---
PRODUCT_PACKAGES += \
    android.hardware.keymaster@4.1 \
    android.hardware.security.keymint \
    android.hardware.security.secureclock \
    android.hardware.security.sharedsecret \
    android.system.keystore2

# The recovery needs the keymaster@4.1 lib relinked into the ramdisk
TW_RECOVERY_ADDITIONAL_RELINK_LIBRARY_FILES += \
    $(TARGET_OUT_SHARED_LIBRARIES)/android.hardware.keymaster@4.1

# --- Gatekeeper (Trustonic) ---
PRODUCT_PACKAGES += \
    android.hardware.gatekeeper@1.0-service

# --- MTK plpath utils (partition linking) ---
PRODUCT_PACKAGES += \
    mtk_plpath_utils \
    mtk_plpath_utils.recovery

# --- Update engine ---
PRODUCT_PACKAGES += \
    update_engine \
    update_engine_sideload \
    update_verifier

# --- Device-specific modules (built from this tree) ---
PRODUCT_PACKAGES += \
    libinit_X6886

# --- formatdata.sh (full /data + /metadata wipe on UI request) ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/system/bin/formatdata.sh:recovery/root/system/bin/formatdata.sh

# --- Kernel modules (display / touch / usb / charger / trustonic / transsion) ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/lib/modules:recovery/root/lib/modules

# --- Touch / WiFi / BT firmware ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/vendor/firmware:vendor/firmware

# --- Trustonic TEE registry (required for decrypt) ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/vendor/app/mcRegistry:vendor/app/mcRegistry

# --- vintf manifests (HAL declarations) ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/system/etc/vintf/manifest.xml:system/etc/vintf/manifest.xml \
    $(LOCAL_PATH)/recovery/root/vendor/etc/vintf/manifest.xml:vendor/etc/vintf/manifest.xml

# --- fstab.emmc (recovery) + fstab.mt6789 (platform) from stock dump ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/first_stage_ramdisk/fstab.emmc:recovery/root/first_stage_ramdisk/fstab.emmc \
    $(LOCAL_PATH)/recovery/root/first_stage_ramdisk/fstab.mt6789:recovery/root/first_stage_ramdisk/fstab.mt6789

# --- ueventd / first stage fstab ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/ueventd.mt6789.rc:recovery/root/ueventd.mt6789.rc \
    $(LOCAL_PATH)/recovery/root/system/etc/ueventd.rc:system/etc/ueventd.rc

# --- init rc files (modules + format wiring) ---
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/root/init.modules.rc:recovery/root/init.modules.rc \
    $(LOCAL_PATH)/recovery/root/init.format.rc:recovery/root/init.format.rc

# --- Blob copy rules (generated by setup-makefiles.sh) ---
-include $(LOCAL_PATH)/proprietary-files.mk
