#!/bin/bash
# setup-makefiles.sh - Infinix Hot 60 Pro Plus (x6886)
# Generates proprietary-files.mk from proprietary-files.txt.
# CRITICAL: de-duplicates every blob so we never produce a duplicate
# PRODUCT_COPY_FILES entry (duplicate entries break the build with
# "duplicated entry" errors). Every source path is kept unique.

set -e
THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$THISDIR/proprietary-files.mk"
SEEN="$THISDIR/.seen_blobs"

: > "$SEEN"
{
    echo "# Auto-generated by setup-makefiles.sh - DO NOT EDIT"
    echo "PRODUCT_COPY_FILES += \\"
    first=1
    while IFS= read -r line; do
        [ -z "$line" ] && continue
        case "$line" in \#*) continue ;; esac
        src="${line%%|*}"
        dst="${line##*|}"
        [ "$dst" = "$line" ] && dst="$(basename "$src")"
        # De-dup: skip if we already emitted this exact source
        if grep -qxF "$src" "$SEEN"; then
            continue
        fi
        echo "$src" >> "$SEEN"
        if [ $first -eq 1 ]; then
            echo "    $THISDIR/proprietary/$src:$TARGET_COPY_OUT_VENDOR/$dst \\"
            first=0
        else
            echo "    $THISDIR/proprietary/$src:$TARGET_COPY_OUT_VENDOR/$dst \\"
        fi
    done < "$THISDIR/proprietary-files.txt"
    echo ""
} > "$OUT"
rm -f "$SEEN"
echo "Wrote $OUT (de-duplicated)"
